### ISSUE TITLE
[BUG] 使用 PhpStorm2023.2 时，文档示例错乱

### ISSUE THREAD

**Issue by shuqingzai** [linjialiang/ps-stubs-doc#1]
文档示例乱掉了，被包含在一个代码块中

![image](https://github.com/linjialiang/ps-stubs-doc/assets/44406033/aa5f2883-9a4f-4658-9708-77eeb7fe7d72)

**Comment by linjialiang** [comment]
> @shuqingzai 这个是phpstorm新版本显示上出了问题，现在已经修复，你可以下载最新版
